name: Pull Request Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install Dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci

      - name: Run Linting
        run: |
          cd backend && (npm run lint || echo "Backend lint skipped")
          cd ../frontend && npm run lint

      - name: Type Check
        run: |
          cd frontend && (npm run type-check || npx tsc --noEmit)

      - name: Build Check
        run: |
          cd frontend && npm run build

      - name: Docker Build Test
        run: |
          docker build -t test-backend ./backend
          docker build -t test-frontend ./frontend

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build and Check Size
        run: |
          cd frontend
          npm run build
          echo "📦 Build completed successfully"
